[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "pytz>=2025.2",
    "reportlab>=4.4.0",
]
